create table teams
(
    id   bigserial   not null,
    name varchar(30) not null,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(100)                            NOT NULL,
    surname   VARCHAR(100)                            NOT NULL,
    team_id   INT                                     NOT NULL,
    is_chosen BOOLEAN                                 NOT NULL,
    last_duel TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT fk_team_user FOREIGN KEY (team_id) REFERENCES teams (id)
);